### ISSUE TITLE
Compilation on Windows 10

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/SpaceSim#1]
SFML directory has been added to PATHS
MingW versions 3.21 & w64 5.0

```
D:/git/SpaceSim/src/main.cpp:5: undefined reference to `_imp___ZN2sf6StringC1EPKcRKSt6locale'
D:/git/SpaceSim/src/main.cpp:5: undefined reference to `_imp___ZN2sf9VideoModeC1Ejjj'
D:/git/SpaceSim/src/main.cpp:5: undefined reference to `_imp___ZN2sf6WindowC1ENS_9VideoModeERKNS_6StringEjRKNS_15ContextSettingsE'
D:/git/SpaceSim/src/main.cpp:16: undefined reference to `_imp___ZN2sf6Window5closeEv'
D:/git/SpaceSim/src/main.cpp:12: undefined reference to `_imp___ZN2sf6Window9pollEventERNS_5EventE'
D:/git/SpaceSim/src/main.cpp:8: undefined reference to `_imp___ZNK2sf6Window6isOpenEv'
D:/git/SpaceSim/src/main.cpp:20: undefined reference to `_imp___ZN2sf6WindowD1Ev'
D:/git/SpaceSim/src/main.cpp:20: undefined reference to `_imp___ZN2sf6WindowD1Ev'
```

**Comment by AdamHarter** [comment]
This appears to be because the SFML modules aren't linked in the proper order, from [SFML Documentation](http://www.sfml-dev.org/tutorials/2.3/start-cb.php):
``When linking to multiple SFML libraries, make sure that you link them in the right order, it is very important for GCC. The rule is that libraries that depend on other libraries must be put first in the list. Every SFML library depends on sfml-system, and sfml-graphics also depends on sfml-window.``
I'm not sure why this works on Linux and not Windows, but the command should be:
```find_package(SFML 2 REQUIRED graphics network audio window system)```

I would test this myself, but I'm too lazy to go find/download/build Eigen3.

**Comment by russleyshaw** [comment]
I am trying to get it to work with the simple example provided on their site. I still get 

C:/Users/Russley/.CLion2016.1/system/cmake/generated/SpaceSim-63a81081/63a81081/Debug/Space.exe: error while loading shared libraries: sfml-window-d-2.dll: cannot open shared object file: No such file or directory


Process finished with exit code -1073741515 (0xC0000135)

**Comment by russleyshaw** [comment]
@AdamHarter if nothing is glaring out at you, its probably some sort of environment problem on my end.

**Comment by AdamHarter** [comment]
This sounds like three possible things:

   1. You didn't build the SFML debug libraries.
   2. The SFML DLL's aren't on your PATH / aren't in the same directory as the executable.
   3. CMake links the DLL's strangely (I don't remember the -2 at the end)

But yeah, it built, so this def. sounds like an environment problem, so I'm going to close this.
